### ISSUE TITLE
Roles werken al in 1.0

### ISSUE THREAD

**Issue by Matthbo** [AO15A1LM/laterna-magica-example#1]
Kevin en ik hadden roles werkend gekregen, dit was zeer simpel te doen, zonder externe packages of iets
Misschien had je effe kunnen bespreken als je heel de applicatie om gaat gooien.

kevin heeft nog niet gecommit maar de oplossing was simple:
Maak een functie isAdmin aan in de user model die true of false returnt, in deze functie wordt gechecked of admin gelijk is aan 'Y', die kan je gebruiken in de middleware om naar de juiste portal te gaan.

Deze repo is dus nu overbodig en hoeft de rest niet opnieuw te beginnen.

**Comment by rickdaalhuizen90** [comment]
Matthijs

Dit is met Kevin vrijdag nog besproken. Hij heeft het naar mij op deze manier gecommuniceerd, en ik citeer "we hebben al wat toe kunnen passen, Maar is nog niet af ".
Zoals jij al aangeeft zijn er hier geen commits van. Dus feitelijk gezien naar aanleiding wat er op de remote branch staat is het nog niet af, en moet ik maar aannemen dat het is opgelost.

Naar aanleiding van die observatie is er een tweede repo aangemaakt. Deze repo beschikt over de functionaliteiten/features die tot zo ver af "horen" te zijn.
Voordat je een conclusie gaat trekken, de Laterna-Magica-2.0 repo fungeert op dit moment alleen nog als een back-up.
Dat betekend dat er nog geen beslissing is gemaakt, of wij dit überhaupt in gebruik zullen nemen.

Mits je de repo heb doorgelezen dan zul je ook zien dat de indeling van de logic en de views maar marginaal zijn veranderd.
Dinsdag beslissen wij als team met welk repo wij verder willen gaan. Mochten er verder nog vragen en-of-opmerkingen zijn, dan hoor ik het vanzelf wel.

P.S In het begin was er al voorgesteld om de Zizaco/Entrust package voor de gebruikers rollen te gebruiken. Dit om verkeerde en/of onveilige implementatie van gebruikers rollen te voorkomen.

**Comment by kfortuin** [comment]
De bestanden van vrijdag staan nu in de repo, dan moeten we nu alles nog samenvoegen. De reden waarom ik nog niks gecommit had is omdat ik niet per ongeluk Rick's werk wilde overschrijven, was van plan dit dinsdag gezamenlijk te doen. Dan moeten we nu dinsdag alles mergen

**Comment by Matthbo** [comment]
Yo Rick

Ik schrok een beetje van deze tweede repo, ik begrijp nu dat alles nog besproken moet worden.
Het klinkt wel een beetje raar als ik hoor dat je vrijdag niet kwam omdat je tot 3 uur s'ochtends bezig was om een simpele functie toe te voegen waar kevin en in binnen een kwartier al mee klaar waren, en dan te zien dat je ineens een nieuwe repo heb gemaakt.

Ik heb me ook niet te veel moeten bemoeien met taken die jullie in een sprint moeten doen, maar van wat ik al qua ervaring heb lijkt dit een aardige omweg.
Snap dat ik alleen maar wil helpen.

**Comment by rickdaalhuizen90** [comment]
No hard feelings @Matthbo , we praten hier maandag of dinsdag over.
